### ISSUE TITLE
Use XDG_DATA_HOME environment variable as default_prefix instead of hardcoded ~/.local/share

### ISSUE THREAD

**Issue by AlexFischbacher** [ponylang/ponyup#136]
Title. By default, `XDG_DATA_HOME` is set to ~/.local/share, but allows users to change their system's default location (for example, I have it as `~/bin`). As far as I am aware, macOS and FreeBSD supports setting these variables as well. I am willing to PR to add this if permitted :)

**Comment by mfelsche** [comment]
Thanks for this suggestion, but this is already handled by using [appdirs](https://github.com/ponylang/appdirs) her: https://github.com/ponylang/ponyup/blob/master/cmd/main.pony#L17

See the corresponding section in the appdirs lib: https://github.com/ponylang/appdirs/blob/master/appdirs/appdirs.pony#L67-L106

**Comment by SeanTAllen** [comment]
I'm reopening this because XDG_DATA_HOME isn't used in ponyup-init.sh which I think could reasonably be called a bug. So this isn't completely implemented.

I think we want to make sure that ponyup-init.sh is using XDG_DATA_HOME the same as the rest of the actual ponyup binary.

@AlexFischbacher if you would be interested in making that happen, a PR would be welcome.

@mfelsche is correct however that the path isn't hardcoded.

**Comment by mfelsche** [comment]
Sorry, i was completely unaware of that particulat script.

**Comment by SeanTAllen** [comment]
@mfelsche quite alright. I almost closed this and was in the process of checking out the script when you closed it.
